### ISSUE TITLE
adjust app names

### ISSUE THREAD

**Issue by bit-pirate** [rosjava/android_apps#19]
We have to correct the apps naming.

**Comment by bit-pirate** [comment]
@stonier what was wrong with the names exactly?

The only divergence I have spotted so far is that the _android_ should be truncated from the app names, e.g. teleop, instead of _android__teleop.

The rest of the package name looks good, i.e. com.github.ros_java.android_apps.APPNAME.

**Comment by stonier** [comment]
That's cool - didn't know you could set tasks in github.

The names problem - probably just a dan memory bug :P
