### ISSUE TITLE
make_a_map depends on map_store messages and services

### ISSUE THREAD

**Issue by bit-pirate** [rosjava/android_apps#20]
How do we get those message into rosjava/android (@stonier any idea)?

Btw, map_store has been catkinized recently: https://github.com/ros-planning/map_store

**Comment by bit-pirate** [comment]
Solved it! I'm such a rosjava guru!

**Comment by bit-pirate** [comment]
NOT! :-D

**Comment by stonier** [comment]
rosjava_messages is a right pain in the ass!

**Comment by bit-pirate** [comment]
Well, once I knww rosjava_messages creates messages for you automatically, then I found it quite cool!

**Comment by stonier** [comment]
Have to recompile everything from the ground up though - that's a royal nuisance.
