### ISSUE TITLE
Duplicate finish requests

### ISSUE THREAD

**Issue by stonier** [rosjava/android_apps#3]
Listener getting duplicate requests for both the listener and robot remocon.

```
Duplicate finish request for ActivityRecord...com.github.robotics_in_concert.rocon_android.robot_remocon/.RobotRemocon
```

**Comment by stonier** [comment]
Was also occuring for standalone Listener.

Apps were calling onDestroy() directly, resulting in two calls to onDestroy() and two calls to stop app on the app manager.

Should never _call_ onDestroy() explicitly. Use finish() instead.

https://github.com/robotics-in-concert/rocon_android/commit/e54e9042c58891ea27aeee08fb5fb77d6138dbb3

**Comment by stonier** [comment]
Still there.

**Comment by stonier** [comment]
Caused by RosActivity itself - threw in a check to see if it is finishing.

https://github.com/ros-java/android_core/commit/ba9c15d33336ba79abfb077d0ff83ed1134f3c80

**Comment by Y-JH** [comment]
Duplicate finish request for ActivityRecord...
出现这种错误的原因是，你在操作关闭当前activity的时候 finish 了两次获更多次。检查一下你的关闭当前页面的代码有没有重复的 finish  。我遇到这个问题了，是因为我不小心在Activity中重写finish方法中 又调用了一次finish方法...

**Comment by adamantivm** [comment]
@Y-JH could you explain a little more what exactly were you trying to do when you had this problem? Which of the android_apps are you trying to use, which version, and what are the steps to produce this problem?

你写简单汉语的话，可能我可以懂你的问题。
