### ISSUE TITLE
Pairing and concert app compatibility

### ISSUE THREAD

**Issue by stonier** [rosjava/android_apps#31]
@corot - this is the discussion thread we need to have about making this happen.

**Comment by stonier** [comment]
Jorge is merging standalone paired, remocon paired and concert app types into one. The primary diffferences include:
- remocon paired uses an application namespace, wheras concert doesn't. 
  - We previously needed that for doing remappings, but we can now do them individually, maybe remove in future.

**Comment by corot** [comment]
Considered done. Not fully tested, however, as only two apps are concertified by now.
