### ISSUE TITLE
map_nav not compile

### ISSUE THREAD

**Issue by talregev** [rosjava/android_apps#40]
android_apps/map_nav/src/main/java/com.github.rosjava.android_apps.map_nav/MapPosePublisherLayer.java:10: error: package move_base_msgs does not exist
import move_base_msgs.MoveBaseActionGoal;

It doesn't recognize  move_base_msgs, even i has at repository folder with jars: org/ros/rosjava_messges/move_base_msgs
and at build.gradle of map_nav i have this line:
compile 'org.ros.rosjava_messages:move_base_msgs:[1.11,1.12)'
and it compile and don't say that this package are missing.

**Comment by stonier** [comment]
Upgraded and fixed this for indigo versions. Working now, but map_nav has a different problem due to an upgrade in the map view/camera view changes damon made a while ago. Need to fix that.

**Comment by talregev** [comment]
Already solve that issue. Don't remeber how.
