### ISSUE TITLE
Error importing the project

### ISSUE THREAD

**Issue by dario-pedro** [rosjava/android_apps#54]
Hello,

When following the [tutorial](http://wiki.ros.org/ApplicationsPlatform/Clients/Android/Tutorials/Getting%20Started) , I got this error:
`Error:Connection timed out: connect. If you are behind an HTTP proxy, please configure the proxy settings either in IDE or Gradle.`

I'm not behind an HTTP proxy. Is the android_apps repository still available ?

**Comment by jubeira** [comment]
That tutorial does not apply anymore; the `android` entrypoint is http://wiki.ros.org/android.
