### ISSUE TITLE
How can I use make a map APP?

### ISSUE THREAD

**Issue by DavidHan008** [rosjava/android_apps#63]
I have rplidar A2. and I want use the APP: make a map?
I run gmapping in my ubuntu .
but in android is nothing map .
I want to save map. but have some Error:
No such service /save_map of type world_canvas_msgs/SaveMap
please help me thx.

**Comment by DavidHan008** [comment]
java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : Unsupported major.minor version 52.0

**Comment by adamantivm** [comment]
@DavidHan008 unfortunately this is too vague and high-level to be able to advise you. 
For general advice I suggest you use [ROS Answers](http://answers.ros.org/), you may get better responses there.
