### ISSUE TITLE
How to use teleop app?

### ISSUE THREAD

**Issue by jrlandau** [rosjava/android_apps#71]
I have been unable to figure out how this app is to be used.  Is there documentation? The wiki is uninformative.

**Comment by jubeira** [comment]
Hi @jrlandau,
it's true that the wiki doesn't give much information about it. I will update it myself when I have some free time, but in the meantime...
- When you turn on the application, you will first see the MasterChooser activity. Write the IP address of your ROS master running (which would probably be the robot) and press "connect"
- Once connected, try listing the topics. You will see `/cmd_vel`, `/compressed_image` among others. Moving the joystick will publish `twist` commands to `/cmd_vel`. You can publish images to `/compressed_image` to visualize the image stream there too.

Does that make sense?

**Comment by jrlandau** [comment]
I did get the robot to move, and I was able to see the cmd_vel messages by
using rostopic echo on the robot.  I don't understand what you are doing
with images at all.  What images?

Is this a rosjava app?

**Comment by jubeira** [comment]
When you connect to the ROS master in the teleop app, you will see not only the joystick but an optional image stream:
![image](https://user-images.githubusercontent.com/2480899/31577819-d9256d22-b0eb-11e7-984a-fe5e5dc300d8.png)
To visualize that in your Android device, you need your robot to publish compressed images to the topic `compressed_image`. If your robot doesn't have a camera or can't publish images, don't worry about it, you can still teleoperate it.

**Comment by jrlandau** [comment]
Thanks--I understand.  I am working with Ubiquity Robotics and have written
a robot control app
<https://play.google.com/store/apps/details?id=com.jrlandau.robotcmdr&hl=en>
with voice control.  So, I'm always interested in what other people have
done.

I will investigate providing the image facility, as you do.

My app is a Cordova app, uses Rosbridge, open src, and is on GitHub
<https://github.com/UbiquityRobotics/Robot_Commander>.

Your comments are welcome.

Joe

**Comment by jubeira** [comment]
@jrlandau interesting! Thanks for the info.

/cc @Shokman @FlorGrosso @eborghi10 ^
