### ISSUE TITLE
Teleop Launch Activity

### ISSUE THREAD

**Issue by TheByteMonster** [rosjava/android_apps#75]
So I am using the app for a project for university, and I can't seem to find the launch activity for the teleop activitiy. The one which says  "Master URI..... Read QRCode.....Connect". That is the the activity that I am having trouble locating. Can anyone point me in the right direction to where the launch activity is?

Thanks

**Comment by jubeira** [comment]
Hi @TheByteMonster! 
[ROS answers](https://answers.ros.org) is probably a better place to ask these kind of questions.

Anyway, here's a brief explanation.
In general, the activities in ROS applications extend [RosActivity](https://github.com/rosjava/android_core/blob/kinetic/android_10/src/org/ros/android/RosActivity.java). Take a look at its constructor. In particular, `startMasterChooser` method: https://github.com/rosjava/android_core/blob/kinetic/android_10/src/org/ros/android/RosActivity.java#L244. 
By default, it will end up starting [MasterChooserActivity](https://github.com/rosjava/android_core/blob/kinetic/android_10/src/org/ros/android/MasterChooser.java) which is the one that you are looking for.

The main point of all of this is that you can start writing your own application on top of `RosActivity` without worrying about how to connect to the ROS master.

Does that make sense?

**Comment by TheByteMonster** [comment]
Hi @jubeira 
Yeah that makes sense. Thanks for clearing it up.
