### ISSUE TITLE
A problem about control turtlebot2 using APP (CANNOT START APP)! HELP!

### ISSUE THREAD

**Issue by LebronGuo23** [rosjava/android_apps#77]
I have been used APP named "Recon Remocon(indigo)" to connect my turtlebot2，and it made Moo successfully...
But when i enter the interface（turtlebot - Android Pairing）and select a other app(such as teleop)，i click on "LAUNCH" it‘s wrong! It said "CANNOT START APP ------App URL is not valid.no protocol:com.github.rosjava.android_apps.teleop.indigo.MainActivity",I only click on "ACCEPT"...
My ros version is "indigo", the Ubuntu is "14.04".the same version with Android App...

Who can help me?
Thank U very much！！！

**Comment by jubeira** [comment]
Please use https://answers.ros.org for questions like these, describing the problem as much as you can.
