### ISSUE TITLE
Could not find method implementation() for arguments [com.github.rosjava.android_remocons:common_tools:[0.3,0.4)] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler

### ISSUE THREAD

**Issue by WestbrookZero** [rosjava/android_apps#84]

**Comment by jubeira** [comment]
`android_remocons:common_tools:0.3.0` is in `rosjava_mvn_repo`: https://github.com/rosjava/rosjava_mvn_repo/tree/master/com/github/rosjava/android_remocons/common_tools.

Please make sure Gradle is updating the dependencies from there.
